spring:
  application:
    name: dona-arana-tienda

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:postgresql://localhost:5432/tienda_dona_arana
    username: d_arana_user
    password: "1111"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.donaarana.tienda: INFO
    org.springframework.security: INFO