spring:
  application:
    name: dona-arana-tienda

  datasource:
    url: jdbc:postgresql://localhost:5432/tienda_dona_arana
    username: d_arana_user
    password: "1111"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: "Tb8S71F4f0EGII8jIkKNSXmqC+eVoWCAF2EuySGPV4s="
  expiration: 86400000

logging:
  level:
    com.donaarana.tienda: DEBUG
    org.springframework.security: DEBUG