spring:
  datasource:
    # Railway variables separadas
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:data.sql

logging:
  level:
    com.donaarana.tienda: INFO
    org.springframework.security: INFO
    root: WARN