spring:
  datasource:
    # Para desarrollo local - URL pública de Railway
    url: jdbc:postgresql://turntable.proxy.rlwy.net:18788/railway
    username: postgres
    password: ${RAILWAY_DB_PASSWORD:1111}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.donaarana.tienda: DEBUG
    org.springframework.security: DEBUG