spring:
  application:
    name: dona-arana-tienda

  main:
    allow-bean-definition-overriding: true

  # Perfil activo por defecto (local)
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    com.donaarana.tienda: INFO
    org.springframework.security: INFO